// ============================================================
// PORTFOLIO DATA - Edit this file to customize your portfolio
// ============================================================

import credlyBadges from "./credly-badges.json";

export const personalInfo = {
  name: "Nidhal El Kebir",
  title: "Cybersecurity Engineering Student — Penetration Testing & Network Security",
  tagline:
    "I find weaknesses before attackers do — then document them clearly enough to fix.",
  typingStrings: [
    "Cybersecurity Engineering Student",
    "Penetration Testing & Network Security",
    "Vulnerability Assessment",
    "Security Auditing & Reporting",
  ],
  email: "nidhalelkebir@gmail.com",
  github: "https://github.com/nidhalelkebir",
  linkedin: "https://linkedin.com/in/nidhalelkebir",
  credly: "https://www.credly.com/users/nidhal-el-kebir",
  cvUrl: "/CV NIDHAL EL KEBIR.pdf",
  bio: `Cybersecurity engineering student specializing in offensive security (pentest), with hands-on practice in identifying network and web vulnerabilities through a personal lab environment. Experienced in network enumeration, traffic analysis, and exploitation of vulnerable Linux machines using Kali Linux. Skilled in documenting vulnerabilities and recommending remediation measures. Seeking a cybersecurity/pentest internship to contribute to security audits and continue strengthening technical skills.`,
};

export const skillGroups = [
  {
    name: "Offensive Security",
    summary: "Assessment work from recon through reporting.",
    items: [
      "Penetration Testing",
      "Vulnerability Assessment",
      "Network Enumeration",
      "Web Application Security (OWASP Top 10)",
      "Privilege Escalation",
      "Post-Exploitation",
      "Security Reporting & Remediation Advice",
    ],
  },
  {
    name: "Defensive Security",
    summary: "Detection and response, backed by the IBM and Cisco tracks.",
    items: [
      "SIEM Monitoring & Log Analysis",
      "Incident Response",
      "Digital Forensics & Evidence Handling",
      "Threat Hunting",
      "Threat Intelligence",
      "Endpoint Detection & Response (EDR)",
      "Malware & Phishing Analysis",
      "Defense in Depth",
    ],
  },
  {
    name: "Network Engineering",
    summary: "Routing, switching, and carrier-side infrastructure.",
    items: [
      "TCP/IP, DNS, DHCP",
      "IPv4 / IPv6 Subnetting",
      "VLANs & Inter-VLAN Routing",
      "Static Routing & OSPF",
      "STP & EtherChannel",
      "First-Hop Redundancy (HSRP)",
      "ACLs & NAT",
      "Wireless LAN Configuration",
      "VPN / IPsec",
      "Fiber & Copper Access Networks",
      "Network Troubleshooting",
    ],
  },
  {
    name: "Systems & Cloud",
    summary: "Platforms I build, harden, and administer.",
    items: [
      "Linux (Kali / Ubuntu)",
      "Windows 10/11",
      "AWS Cloud Foundations",
      "AWS Cloud Security",
      "Identity & Access Management (IAM)",
      "Endpoint Hardening",
      "Account Provisioning",
      "Virtualization (VirtualBox / VMware)",
      "Containers",
    ],
  },
  {
    name: "Security Tooling",
    summary: "Day-to-day instruments across offense, defense, and analysis.",
    items: [
      "Nmap",
      "Wireshark",
      "Metasploit",
      "Burp Suite",
      "IBM QRadar (SIEM)",
      "Fortinet FortiGate (NGFW)",
      "Cisco Packet Tracer",
      "Gobuster",
      "Hydra",
      "John the Ripper",
      "Scapy",
    ],
  },
  {
    name: "Cryptography & Data",
    summary: "Protecting data at rest and in transit.",
    items: [
      "Encryption Methods",
      "Cryptographic Protocols",
      "Public Key Infrastructure (PKI)",
      "Database Security",
      "SQL Injection Defence",
      "Password & Authentication Policies",
    ],
  },
  {
    name: "Development & Automation",
    summary: "Scripting and tooling I write to speed up the work.",
    items: ["Python", "Bash", "JavaScript / TypeScript", "PHP", "SQL", "Git"],
  },
];

export type Certification = {
  id: string;
  title: string;
  issuer: string;
  authorizedBy: string | null;
  date: string;
  level: string | null;
  description: string;
  skills: string[];
  image: string;
  credentialUrl: string;
};

// Generated by scripts/fetch-credly.mjs from the public Credly profile — `npm run credly` refreshes it.
export const certifications: Certification[] = credlyBadges as Certification[];

export const experiences = [
  {
    id: "exp-1",
    role: "IT Technician Intern",
    organization: "Aeroport Monastir (TAV)",
    period: "2023",
    summary:
      "Supported security hardening through system updates, antivirus management, and user account administration. Provided technical assistance, troubleshooting, and workstation/peripheral maintenance for daily operations.",
    tags: ["System Hardening", "Windows Support", "Account Administration"],
  },
  {
    id: "exp-2",
    role: "Computer Technician",
    organization: "Almaarif Company",
    period: "2024",
    summary:
      "Installed and maintained Windows workstations and peripherals while ensuring reliability and performance. Performed basic network configuration including IP addressing, gateway, DNS, and network sharing.",
    tags: ["Windows", "Networking", "IT Operations"],
  },
  {
    id: "exp-3",
    role: "Web Developer",
    organization: "PSI INFO",
    period: "2025",
    summary:
      "Participated in web application module development, gained foundational database and application-logic knowledge, and performed functional testing and bug fixing. Built awareness of common vulnerabilities such as XSS and injection issues.",
    tags: ["Web Development", "Testing", "Web Security Basics"],
  },
  {
    id: "exp-4",
    role: "Networking Intern",
    organization: "Tunisie Telecom",
    period: "June 2026",
    summary:
      "Worked alongside network technicians on the operator's access and transmission infrastructure. Assisted with router and switch configuration, IP addressing plans, and subscriber link troubleshooting across fiber and copper access networks, while observing supervision and incident-handling procedures in a live production environment.",
    tags: ["Routing & Switching", "Access Networks", "Network Troubleshooting"],
  },
];

// Sourced from github.com/nidhalelkebir — descriptions follow each repo's README.
export const projects = [
  {
    id: "proj-configdoctor",
    title: "ConfigDoctor",
    role: "Security CLI · published on npm",
    description:
      "Configuration scanner that audits .env, .json, .yaml, and .ini files for hardcoded secrets, weak credentials, dangerous defaults, and CORS misconfigurations. Rule-based and fully local — no cloud calls — with coloured console output and JSON for CI/CD gating.",
    technologies: ["TypeScript", "Node.js", "CLI", "CI/CD"],
    github: "https://github.com/nidhalelkebir/ConfigDoctor",
    demo: "https://www.npmjs.com/package/configdoctor",
  },
  {
    id: "proj-cybereye",
    title: "CyberEye",
    role: "Network traffic analyzer",
    description:
      "Real-time traffic analyzer built on raw sockets with an optional Scapy backend. Classifies protocols, tracks top talkers, and flags port scans, DDoS-style bursts, and behavioural anomalies against a learned packets-per-second baseline. Ships terminal and GUI dashboards plus offline CSV analysis.",
    technologies: ["Python", "Scapy", "Raw Sockets", "Tkinter"],
    github: "https://github.com/nidhalelkebir/CyberEye",
    demo: "#",
  },
  {
    id: "proj-pycvescanner",
    title: "PyCVEScanner",
    role: "Vulnerability assessment tool",
    description:
      "Scans hosts and installed software for known vulnerabilities: port scanning with banner grabbing for service and version identification, then live lookups against the NVD API v2. Interprets CVSS base scores into severity tiers and exports text, JSON, and HTML reports.",
    technologies: ["Python", "NVD API", "CVSS", "Reporting"],
    github: "https://github.com/nidhalelkebir/DaAnalayzR",
    demo: "#",
  },
  {
    id: "proj-fivem-scanner",
    title: "FiveM Resource Security Scanner",
    role: "Static malware analysis",
    description:
      "Static analyzer that audits Lua and JavaScript game-server resources for backdoors. Detects dynamic code execution (loadstring, pcall abuse), obfuscation via string.char/hex/base64, exfiltration through HTTP calls and Discord webhooks, privilege escalation via ACE permissions, and filesystem or process abuse.",
    technologies: ["Python", "Static Analysis", "Regex", "Tkinter"],
    github: "https://github.com/nidhalelkebir/FivemBackdoorAnalyzer",
    demo: "#",
  },
  {
    id: "proj-whytracker",
    title: "WhyTracker",
    role: "Developer tooling in Go",
    description:
      "A decision-debt tracker: it captures technical decisions with their context, assumptions, and expiry triggers, then flags them once those assumptions go stale. CLI-first with plain-text YAML storage so the history stays diffable in version control.",
    technologies: ["Go", "CLI", "YAML"],
    github: "https://github.com/nidhalelkebir/WhyTracker",
    demo: "#",
  },
  {
    id: "proj-learnsphere",
    title: "LearnSphere",
    role: "Full-stack platform (prototype)",
    description:
      "Learning management platform with authentication and role-based dashboards for students, teachers, and administrators. Covers a course catalogue, interactive lessons, quizzes with scoring, notifications, and platform analytics.",
    technologies: ["React", "Firebase", "Tailwind CSS", "Framer Motion"],
    github: "https://github.com/nidhalelkebir/LearnSphere",
    demo: "#",
  },
];

export type Lab = {
  id: string;
  title: string;
  platform: string;
  difficulty: "Easy" | "Medium" | "Hard";
  date: string;
  duration: string;
  summary: string;
  techniques: string[];
  /** YouTube watch/share URL. Leave empty until the recording is published. */
  videoUrl: string;
  /** Optional link to a written report. */
  writeupUrl?: string;
};

// Add a lab here, drop in the YouTube link, and it appears on the site.
export const labs: Lab[] = [
  {
    id: "lab-metasploitable2",
    title: "Metasploitable 2 — Full Compromise",
    platform: "Self-hosted lab",
    difficulty: "Easy",
    date: "2026",
    duration: "—",
    summary:
      "Host discovery and full service enumeration with Nmap, exploitation of vulnerable FTP, SMB, and Apache services through Metasploit, then post-exploitation and privilege escalation to root.",
    techniques: ["Nmap", "Metasploit", "Service Enumeration", "Privilege Escalation"],
    videoUrl: "",
  },
  {
    id: "lab-hackable1",
    title: "Hackable 1 — Boot2Root",
    platform: "Self-hosted lab",
    difficulty: "Easy",
    date: "2026",
    duration: "—",
    summary:
      "Reconnaissance and web enumeration with Gobuster, exploitation of a misconfigured service to land a reverse shell, then privilege escalation to root.",
    techniques: ["Gobuster", "Reverse Shell", "Netcat", "Linux PrivEsc"],
    videoUrl: "",
  },
  {
    id: "lab-hackable2",
    title: "Hackable 2 — Boot2Root",
    platform: "Self-hosted lab",
    difficulty: "Medium",
    date: "2026",
    duration: "—",
    summary:
      "Port scanning and web application analysis, directory brute-forcing, FTP exploitation and command injection, finishing with root escalation through a SUID binary.",
    techniques: ["Burp Suite", "Command Injection", "FTP Exploitation", "SUID Abuse"],
    videoUrl: "",
  },
];

export const stats = [
  { label: "Verified certifications", value: certifications.length, suffix: "" },
  { label: "Professional internships", value: 4, suffix: "" },
  { label: "Projects shipped", value: projects.length, suffix: "" },
  { label: "Languages spoken", value: 3, suffix: "" },
];

export const terminalCommands: Record<string, string> = {
  help: `Available commands:

  whoami     - Identity and current focus
  about      - Professional summary
  skills     - Technical proficiency matrix
  certs      - Verified certifications (live from Credly)
  experience - Internship history
  projects   - Security tooling and assessments
  contact    - Direct contact channels
  clear      - Clear the session`,

  whoami: `ghost@nidhal:~$ id
  name    : ${personalInfo.name}
  role    : Cybersecurity Engineering Student
  focus   : Penetration Testing / Network Security
  status  : Seeking a cybersecurity internship
  handle  : ghost`,

  about: `PROFESSIONAL SUMMARY
────────────────────────────────────────────

${personalInfo.bio}

Type 'skills' for the technical breakdown.`,

  skills: `TECHNICAL CAPABILITIES
────────────────────────────────────────────

${skillGroups
  .map((g) => `[${g.name}]\n` + g.items.map((i) => `  · ${i}`).join("\n"))
  .join("\n\n")}`,

  certs: `VERIFIED CERTIFICATIONS — ${certifications.length} total
────────────────────────────────────────────

${certifications
  .map((c) => `  [✓] ${c.title}\n      ${c.issuer} · ${c.date}`)
  .join("\n")}

  Verify: ${personalInfo.credly}`,

  experience: `INTERNSHIP HISTORY
────────────────────────────────────────────

${experiences
  .map((e) => `  [${e.period}] ${e.role}\n         ${e.organization}\n         ${e.tags.join(" · ")}`)
  .join("\n\n")}`,

  projects: `SECURITY PROJECTS — ${projects.length} total
────────────────────────────────────────────

${projects
  .map(
    (p, i) =>
      `  [${String(i + 1).padStart(2, "0")}] ${p.title}\n       ${p.technologies.join(", ")}`
  )
  .join("\n")}

Scroll to the Projects section for full case studies.`,

  contact: `CONTACT CHANNELS
────────────────────────────────────────────

  Email    : ${personalInfo.email}
  GitHub   : ${personalInfo.github}
  LinkedIn : ${personalInfo.linkedin}
  Credly   : ${personalInfo.credly}

Available for internships and security collaborations.`,
};
